version: '3.8'

services:
  qwen-api:
    build: .
    image: ghcr.io/water008/qwenapi:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 600s
      timeout: 10s
      retries: 3
      start_period: 40s
